# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2024-06-13 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=40)),
            ],
        ),
    ]
