# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2024-06-13 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
