# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2024-06-14 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('sno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=40)),
                ('sbirthdate', models.DateField()),
                ('scollege', models.CharField(max_length=40)),
                ('sgrade', models.IntegerField()),
                ('smajor', models.CharField(max_length=60)),
                ('spasswd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('tno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=40)),
                ('tbirthdate', models.DateField()),
                ('tcollege', models.CharField(max_length=40)),
                ('tpasswd', models.CharField(max_length=100)),
            ],
        ),
    ]
