# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2024-06-14 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sgrade',
            field=models.CharField(max_length=4),
        ),
    ]
