# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2024-06-14 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20240614_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ssex',
            field=models.CharField(choices=[('m', '男'), ('f', '女')], default='男', max_length=2),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tsex',
            field=models.CharField(choices=[('m', '男'), ('f', '女')], default='男', max_length=2),
        ),
    ]
