# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2024-06-16 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20240614_2256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentUser',
        ),
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.CharField(default='0000000', max_length=7, verbose_name='院内编号'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='number',
            field=models.CharField(default='0000000', max_length=7, verbose_name='院内编号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sbirthdate',
            field=models.DateField(verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='scollege',
            field=models.CharField(choices=[('计算机学院', '计算机学院'), ('自动化学院', '自动化学院'), ('航天学院', '航天学院'), ('数学学院', '数学学院')], max_length=40, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sgrade',
            field=models.CharField(max_length=4, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='smajor',
            field=models.CharField(max_length=60, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=40, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sno',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='spasswd',
            field=models.CharField(max_length=100, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ssex',
            field=models.CharField(choices=[('m', '男'), ('f', '女')], default='男', max_length=2, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tbirthdate',
            field=models.DateField(verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tcollege',
            field=models.CharField(choices=[('计算机学院', '计算机学院'), ('自动化学院', '自动化学院'), ('航天学院', '航天学院'), ('数学学院', '数学学院')], max_length=40, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tname',
            field=models.CharField(max_length=40, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tno',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='教职工号'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tpasswd',
            field=models.CharField(max_length=100, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tsex',
            field=models.CharField(choices=[('m', '男'), ('f', '女')], default='男', max_length=2, verbose_name='性别'),
        ),
    ]
