# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2024-06-17 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20240617_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('cno', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='课程号')),
                ('cname', models.CharField(max_length=60, verbose_name='课程名')),
                ('ccredit', models.IntegerField(verbose_name='学分')),
                ('pcno', models.CharField(max_length=20, verbose_name='先修课程')),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.teacher', verbose_name='教师')),
            ],
        ),
        migrations.CreateModel(
            name='SC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='成绩')),
                ('semester', models.CharField(max_length=5, verbose_name='学期')),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.course', verbose_name='学号')),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='login.student', verbose_name='课程号')),
            ],
        ),
    ]
