# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2024-06-17 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_course_sc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cno',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='课程号'),
        ),
    ]
