# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2024-06-18 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20240617_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pcno',
            field=models.CharField(help_text='如果有先修课程，请填写对应先修课程课程号，否则留空', max_length=20, null=True, verbose_name='先修课程'),
        ),
    ]
