# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2024-06-18 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20240618_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pcno',
            field=models.CharField(blank=True, help_text='如果有先修课程，请填写对应先修课程课程号，否则留空', max_length=20, null=True, verbose_name='先修课程'),
        ),
    ]
