# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2024-06-18 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20240618_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ccredit',
            field=models.FloatField(verbose_name='学分'),
        ),
    ]
