# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2024-06-18 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20240618_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sc',
            name='grade',
            field=models.IntegerField(null=True, verbose_name='成绩'),
        ),
    ]
