# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2024-06-19 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_course_grading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grading',
            field=models.BooleanField(default=False, verbose_name='是否打分'),
        ),
    ]
