# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2024-06-19 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20240619_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ccredit',
            field=models.IntegerField(verbose_name='学分'),
        ),
    ]
